sed -i '429,446c\
                context = context,\
                post = post,\
                template = template,\
                bgImageUrl = bgImageUrl,\
                overlayAlpha = overlayAlpha,\
                textAlignName = textAlignName,\
                fontName = fontName,\
                fontSizeSp = fontSizeSp,\
                lineSpacingMult = lineSpacingMult,\
                customCategory = customCategory,\
                customText = customText,\
                customRef = customRef,\
                customTitleColor = customTitleColor,\
                customTextColor = customTextColor,\
                customRefColor = customRefColor,\
                showLogo = showLogo,\
                showWatermark = showWatermark\
' app/src/main/java/com/example/utils/PostShareUtil.kt
