package com.example.utils

/**
 * High-performance, centralized multi-language localization dictionary
 * Supporting Bangla (bn), English (en), and Arabic (ar) for all Menu & Settings screens.
 */
object SettingsLocalization {

    const val LANG_BN = "bn"
    const val LANG_EN = "en"
    const val LANG_AR = "ar"

    fun get(key: String, lang: String): String {
        val strings = when (lang) {
            LANG_EN -> EN_STRINGS
            LANG_AR -> AR_STRINGS
            else -> BN_STRINGS
        }
        return strings[key] ?: BN_STRINGS[key] ?: EN_STRINGS[key] ?: key
    }

    fun format(key: String, lang: String, vararg args: Any): String {
        val template = get(key, lang)
        return try {
            String.format(template, *args)
        } catch (e: Exception) {
            template
        }
    }

    // --- BENGALI (বাংলা) STRINGS ---
    private val BN_STRINGS = mapOf(
        // Menu & General
        "menu_title" to "মেনু অপশন",
        "close" to "বন্ধ করুন",
        "back" to "ফিরে যান",
        "save" to "সংরক্ষণ করুন",
        "cancel" to "বাতিল",
        "delete" to "মুছে ফেলুন",
        "edit" to "সম্পাদনা",
        "search" to "অনুসন্ধান",
        "details" to "বিস্তারিত",
        "confirm" to "নিশ্চিত করুন",
        "done" to "সম্পন্ন",
        "share" to "শেয়ার করুন",
        "download" to "ডাউনলোড",
        "refresh" to "রিফ্রেশ",
        "all" to "সবগুলো",
        "enabled" to "চালু",
        "disabled" to "বন্ধ",
        "system_default" to "সিস্টেম ডিফল্ট",
        "reset" to "রিসেট",
        "play" to "প্লে",
        "pause" to "পজ",
        "copy" to "কপি করুন",
        "copied" to "কপি করা হয়েছে",
        "success" to "সফল",
        "error" to "ত্রুটি",
        "loading" to "লোড হচ্ছে...",
        "profile_title" to "আমার প্রোফাইল",
        "profile_stats" to "প্রোফাইল ও পড়ার পরিসংখ্যান",
        "profile_desc" to "কুরআন পাঠের অগ্রগতি ও ব্যক্তিগত তথ্য",
        
        // Menu Categories
        "cat_quran_media" to "কুরআন শিক্ষা ও মিডিয়া",
        "cat_dua_worship" to "দুআ ও ইবাদত",
        "cat_personal_tools" to "ব্যক্তিগত টুলস",
        "cat_app_settings" to "অ্যাপ সিস্টেম ও সেটিংস",

        // Menu Items
        "item_subjectwise" to "বিষয়ভিত্তিক কুরআন",
        "item_learn" to "কুরআন শিক্ষা",
        "item_hifz" to "কুরআন হিফজ ট্র্যাকার",
        "item_player" to "কুরআন অডিও প্লেয়ার",
        "item_video" to "কুরআন ভিডিও এডিটর",
        "item_dua" to "কুরআনিক দুআ",
        "item_morning_evening_dua" to "সকাল সন্ধ্যার দুআ ও জিকির",
        "item_mosque" to "নিকটবর্তী মসজিদ",
        "item_manzil" to "মানযিল ও আয়াতুশ শিফা",
        "item_qibla" to "কিবলা কম্পাস",
        "item_prayer_times" to "নামাজের সময়সূচি",
        "item_prayer_alarms" to "নামাজ ও আজান অ্যালার্ম",
        "item_calendar" to "ইসলামিক হিজরি ক্যালেন্ডার",
        "item_planner" to "কুরআন খতম প্ল্যানার",
        "item_bookmark" to "বুকমার্ক তালিকা",
        "item_note" to "আমার নোটপ্যাড",
        "item_game" to "কুরআনিক শব্দ গেম",
        "item_language" to "ভাষা নির্বাচন (Language)",
        "item_font_settings" to "ফন্ট ও তাজভীদ সেটিংস",
        "item_theme" to "অ্যাপ থিম নির্বাচন",
        "item_notifications" to "নোটিফিকেশন সেটিংস",
        "item_offline_sync" to "কুরআন অফলাইন ডাউনলোড",
        "item_backup" to "ব্যাকআপ ও রিস্টোর",
        "item_about" to "আমাদের সম্পর্কে ও প্রাইভেসি",
        "item_contact" to "যোগাযোগ ও মতামত",

        // Quick Settings
        "quick_settings_title" to "দ্রুত সেটিংস ও নিয়ন্ত্রণ",
        "quick_lang_label" to "অ্যাপের ভাষা",
        "quick_font_label" to "কুরআনের ফন্ট",
        "quick_theme_label" to "থিম মোড",
        "quick_screen_on_label" to "পড়ার সময় স্ক্রিন অন রাখুন",

        // Language Screen
        "lang_screen_title" to "ভাষা নির্বাচন / Language",
        "lang_banner_title" to "অ্যাপের ভাষা নির্বাচন",
        "lang_banner_desc" to "আপনার পছন্দের ভাষা নির্বাচন করুন। পুরো অ্যাপ নির্বাচিত ভাষায় প্রদর্শিত হবে।",
        "lang_bn_title" to "বাংলা",
        "lang_bn_desc" to "বাংলা (Bengali) - ডিফল্ট ইন্টারফেস",
        "lang_en_title" to "English",
        "lang_en_desc" to "English - International UI",
        "lang_ar_title" to "العربية",
        "lang_ar_desc" to "العربية (Arabic) - الواجهة العربية بالكامل",
        "lang_switched_bn" to "ভাষা পরিবর্তন করে 'বাংলা' করা হয়েছে",
        "lang_switched_en" to "Language changed to English",
        "lang_switched_ar" to "تم تغيير لغة التطبيق إلى العربية",

        // Theme Screen
        "theme_screen_title" to "অ্যাপ থিম নির্বাচন",
        "theme_banner_title" to "থিম ও ডিসপ্লে মোড",
        "theme_banner_desc" to "আপনার চোখের আরাম ও পাঠের সুবিধার্থে পছন্দমতো থিম বেছে নিন।",
        "theme_system" to "সিস্টেম ডিফল্ট",
        "theme_system_desc" to "ডিভাইসের সিস্টেম সেটিংস অনুযায়ী স্বয়ংক্রিয়ভাবে পরিবর্তিত হবে",
        "theme_light" to "লাইট মোড (Light)",
        "theme_light_desc" to "উজ্জ্বল ও পরিষ্কার সাদা ব্যাকগ্রাউন্ড",
        "theme_dark" to "ডার্ক মোড (Dark)",
        "theme_dark_desc" to "রাতের পড়ার জন্য চোখের উপযোগী শান্ত ডার্ক লুক",
        "theme_oled" to "ওলেড ব্ল্যাক (OLED Black)",
        "theme_oled_desc" to "গভীর কালো ব্যাকগ্রাউন্ড, ব্যাটারি সাশ্রয়ী",
        "theme_sepia" to "সেপিয়া মোড (Sepia)",
        "theme_sepia_desc" to "ঐতিহ্যবাহী কাগজের মত আরামদায়ক উষ্ণ সেপিয়া লুক",

        // Font & Tajweed Screen
        "font_screen_title" to "ফন্ট ও তাজভীদ সেটিংস",
        "tab_arabic_font" to "আরবি ফন্ট ও স্ক্রিপ্ট",
        "tab_trans_font" to "অনুবাদ ও উচ্চারণ",
        "tab_tajweed_rules" to "তাজভীদ কালার গাইড",
        "arabic_font_style" to "আরবি ফন্ট স্টাইল",
        "arabic_script_style" to "কুরআন স্ক্রিপ্ট স্টাইল",
        "arabic_font_size" to "আরবি হরফের আকার",
        "arabic_line_spacing" to "আরবি লাইনের দূরত্ব (Line Spacing)",
        "trans_font_size" to "অনুবাদ হরফের আকার",
        "trans_font_style" to "বাংলা ফন্ট স্টাইল",
        "show_translation" to "অনুবাদ প্রদর্শন করুন",
        "show_transliteration" to "উচ্চারণ (Transliteration) প্রদর্শন",
        "show_tajweed" to "রঙিন তাজভীদ রুলস চালু রাখুন",
        "show_waqf" to "থামার চিহ্ন (ওয়াকফ) স্পষ্ট করুন",
        "font_preview_title" to "প্রিভিউ (পূর্বরূপ)",
        "font_preview_arabic" to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "font_preview_trans" to "পরম করুণাময় ও অসীম দয়ালু আল্লাহর নামে শুরু করছি।",
        "reset_font_defaults" to "ডিফল্ট সেটিংসে ফিরিয়ে নিন",

        // Notifications Screen
        "notif_screen_title" to "নোটিফিকেশন সেটিংস",
        "notif_banner_title" to "স্মার্ট ইসলামিক রিমাইন্ডার",
        "notif_banner_desc" to "দৈনিক আয়াত, হাদিস, বিশেষ ইভেন্ট ও জিকিরের সময়মতো নোটিফিকেশন পান।",
        "notif_daily_ayah" to "দৈনিক কুরআনের আয়াত",
        "notif_daily_ayah_desc" to "প্রতিদিন নির্দিষ্ট সময়ে নির্বাচিত কুরআনিক আয়াত ও অনুবাদ",
        "notif_daily_hadith" to "দৈনিক হাদিস ও নসিহত",
        "notif_daily_hadith_desc" to "সহিহ হাদিস ও প্রাত্যহিক অনুপ্রেরণামূলক ইসলামিক বার্তা",
        "notif_islamic_events" to "ইসলামিক বিশেষ দিবস ও ইভেন্ট",
        "notif_islamic_events_desc" to "শুক্রবার, লাইলাতুল কদর, শবে বরাত, আশুরা ও ঈদের রিমাইন্ডার",
        "notif_durood" to "দরূদ শরীফ রিমাইন্ডার",
        "notif_durood_desc" to "নবীজী ﷺ এর ওপর দরূদ পাঠের নিয়মিত স্বত্বর সতর্কবার্তা",
        "notif_istighfar" to "ইস্তিগফার ও তওবা রিমাইন্ডার",
        "notif_istighfar_desc" to "দৈনিক আত্মশুদ্ধি ও ক্ষমার জন্য জিকির রিমাইন্ডার",
        "notif_sound_label" to "নোটিফিকেশন সাউন্ড",
        "notif_vibrate_label" to "ভাইব্রেশন (কম্পন)",
        "notif_time_select" to "সময় নির্ধারণ করুন",
        "notif_interval_select" to "পুনরাবৃত্তির সময়কাল",

        // Profile & Stats
        "stats_read_time" to "মোট পাঠের সময়",
        "stats_surahs_read" to "পঠিত সূরা",
        "stats_total_ayahs" to "পঠিত আয়াত",
        "stats_streak" to "টানা পড়ার দিন (Streak)",
        "stats_bookmarks" to "মোট বুকমার্ক",
        "stats_notes" to "তৈরিকৃত নোট",
        "stats_khatam_count" to "খতম সম্পন্ন",
        "profile_edit_name" to "নাম পরিবর্তন করুন",
        "profile_user_placeholder" to "কুরআনের পাঠক",

        // Bookmarks & Notes
        "bookmarks_empty" to "এখনো কোনো বুকমার্ক সংরক্ষণ করা হয়নি",
        "bookmarks_empty_desc" to "সূরা, আয়াত বা মুসহাফ পড়ার সময় বুকমার্ক আইকনে ট্যাপ করে সংরক্ষণ করুন।",
        "notes_empty" to "আপনার নোটপ্যাড এখনো খালি",
        "notes_empty_desc" to "কুরআন অধ্যয়ন ও চিন্তাভাবনার গুরুত্বপূর্ণ বিষয়গুলো এখানে নোট করে রাখুন।",
        "new_note" to "নতুন নোট লিখুন",
        "note_title_hint" to "নোটের শিরোনাম...",
        "note_body_hint" to "আপনার চিন্তা, তাফসির পয়েন্ট বা ব্যক্তিগত উপলব্ধি লিখুন...",
        "note_saved" to "নোট সফলভাবে সংরক্ষিত হয়েছে",
        "note_deleted" to "নোট মুছে ফেলা হয়েছে",

        // Planner Screen
        "planner_title" to "কুরআন খতম প্ল্যানার",
        "planner_target" to "খতমের লক্ষ্য ও পরিকল্পনা",
        "planner_daily_target" to "দৈনিক পড়ার লক্ষ্য",
        "planner_days_left" to "দিন বাকি আছে",
        "planner_progress" to "সামগ্রিক অগ্রগতি",
        "planner_mark_today_done" to "আজকের পড়া সম্পন্ন হিসেবে চিহ্নিত করুন",
        "planner_reset" to "প্ল্যানার রিসেট করুন",

        // Offline Download Screen
        "offline_title" to "কুরআন অফলাইন ডাউনলোড",
        "offline_desc" to "ইন্টারনেট ছাড়াও যেকোনো সময় সম্পূর্ণ কুরআন তিলাওয়াত ও তাফসির উপভোগ করতে প্রয়োজনীয় ফাইল ডাউনলোড করুন।",
        "offline_mushaf_pages" to "মুসহাফ পৃষ্ঠা ও ইমেজ",
        "offline_audio" to "অডিও তিলাওয়াত (ক্বারীভিত্তিক)",
        "offline_tafsir" to "তাফসির ও শব্দার্থ ডেটা",
        "offline_storage_used" to "ব্যবহৃত স্টোরেজ",
        "offline_download_all" to "সম্পূর্ণ অফলাইন প্যাকেজ ডাউনলোড করুন",
        "offline_clear_cache" to "ক্যাশ পরিষ্কার করুন",

        // Backup & Restore
        "backup_title" to "ব্যাকআপ ও রিস্টোর",
        "backup_desc" to "আপনার বুকমার্ক, নোটপ্যাড এবং পড়ার অগ্রগতি সুরক্ষিত রাখুন।",
        "backup_create" to "নতুন ব্যাকআপ তৈরি করুন",
        "backup_restore" to "ব্যাকআপ ফাইল থেকে রিস্টোর করুন",
        "backup_last_date" to "সর্বশেষ ব্যাকআপের তারিখ: %s",
        "backup_success" to "ব্যাকআপ সফলভাবে সম্পন্ন হয়েছে",
        "backup_restore_success" to "ডাটা সফলভাবে রিস্টোর করা হয়েছে",

        // About & Contact
        "about_title" to "আমাদের সম্পর্কে ও প্রাইভেসি",
        "about_app_desc" to "একটি বিজ্ঞাপনমুক্ত, বিশুদ্ধ ও প্রিমিয়াম কুরআন রিডার ও ইসলামিক প্ল্যাটফর্ম। আমাদের মূল লক্ষ্য শুদ্ধ তিলাওয়াত, সহজ অনুধাবন ও আত্মিক উন্নয়ন সহজতর করা।",
        "about_features_title" to "প্রধান বৈশিষ্ঠ্যসমূহ",
        "about_developer_title" to "ডেভেলপমেন্ট ও ক্রেডিট",
        "about_privacy_policy" to "প্রাইভেসি পলিসি ও শর্তাবলী",
        "contact_title" to "যোগাযোগ ও মতামত",
        "contact_desc" to "অ্যাপ সম্পর্কিত যেকোনো পরামর্শ, ভুল সংশোধন বা ফিডব্যাকের জন্য আমাদের সাথে যোগাযোগ করুন।",
        "contact_email" to "ইমেইল পাঠান",
        "contact_telegram" to "টেলিগ্রাম চ্যানেল",
        "contact_facebook" to "ফেসবুক কমিউনিটি",
        "contact_send_msg" to "সরাসরি বার্তা পাঠান",
        "contact_subject_hint" to "বিষয়...",
        "contact_message_hint" to "আপনার মতামত বা বার্তা লিখুন..."
    )

    // --- ENGLISH (ENGLISH) STRINGS ---
    private val EN_STRINGS = mapOf(
        // Menu & General
        "menu_title" to "Menu Options",
        "close" to "Close",
        "back" to "Back",
        "save" to "Save",
        "cancel" to "Cancel",
        "delete" to "Delete",
        "edit" to "Edit",
        "search" to "Search",
        "details" to "Details",
        "confirm" to "Confirm",
        "done" to "Done",
        "share" to "Share",
        "download" to "Download",
        "refresh" to "Refresh",
        "all" to "All",
        "enabled" to "Enabled",
        "disabled" to "Disabled",
        "system_default" to "System Default",
        "reset" to "Reset",
        "play" to "Play",
        "pause" to "Pause",
        "copy" to "Copy",
        "copied" to "Copied to clipboard",
        "success" to "Success",
        "error" to "Error",
        "loading" to "Loading...",
        "profile_title" to "My Profile",
        "profile_stats" to "Profile & Reading Stats",
        "profile_desc" to "Quran reading progress & personal insights",

        // Menu Categories
        "cat_quran_media" to "Quran Study & Media",
        "cat_dua_worship" to "Dua & Worship",
        "cat_personal_tools" to "Personal Tools",
        "cat_app_settings" to "App System & Settings",

        // Menu Items
        "item_subjectwise" to "Subjectwise Quran",
        "item_learn" to "Quran Learning",
        "item_hifz" to "Hifz Tracker",
        "item_player" to "Audio Player",
        "item_video" to "Video Creator",
        "item_dua" to "Quranic Duas",
        "item_morning_evening_dua" to "Morning & Evening Duas",
        "item_mosque" to "Nearby Mosques",
        "item_manzil" to "Manzil & Shifa",
        "item_qibla" to "Qibla Compass",
        "item_prayer_times" to "Prayer Times",
        "item_prayer_alarms" to "Prayer & Azan Alarms",
        "item_calendar" to "Islamic Calendar",
        "item_planner" to "Quran Planner",
        "item_bookmark" to "Bookmarks",
        "item_note" to "My Notepad",
        "item_game" to "Word Game",
        "item_language" to "App Language",
        "item_font_settings" to "Font & Tajweed",
        "item_theme" to "App Theme",
        "item_notifications" to "Notifications",
        "item_offline_sync" to "Offline Download",
        "item_backup" to "Backup & Restore",
        "item_about" to "About Us & Privacy",
        "item_contact" to "Contact & Support",

        // Quick Settings
        "quick_settings_title" to "Quick Settings & Controls",
        "quick_lang_label" to "App Language",
        "quick_font_label" to "Quranic Font",
        "quick_theme_label" to "Theme Mode",
        "quick_screen_on_label" to "Keep Screen On while Reading",

        // Language Screen
        "lang_screen_title" to "Language Settings",
        "lang_banner_title" to "App Language",
        "lang_banner_desc" to "Select your preferred language for the entire app interface.",
        "lang_bn_title" to "বাংলা",
        "lang_bn_desc" to "বাংলা (Bengali) - Default Interface",
        "lang_en_title" to "English",
        "lang_en_desc" to "English - International UI",
        "lang_ar_title" to "العربية",
        "lang_ar_desc" to "العربية (Arabic) - Complete Arabic Interface",
        "lang_switched_bn" to "Language changed to Bangla",
        "lang_switched_en" to "Language changed to English",
        "lang_switched_ar" to "Language changed to Arabic",

        // Theme Screen
        "theme_screen_title" to "App Theme Selection",
        "theme_banner_title" to "Theme & Display Mode",
        "theme_banner_desc" to "Choose your preferred reading theme for optimal visual comfort.",
        "theme_system" to "System Default",
        "theme_system_desc" to "Follows device system dark/light configuration",
        "theme_light" to "Light Mode",
        "theme_light_desc" to "Bright and crisp white background",
        "theme_dark" to "Dark Mode",
        "theme_dark_desc" to "Calm dark background designed for night reading",
        "theme_oled" to "OLED Black",
        "theme_oled_desc" to "Pure pitch-black background, saves battery",
        "theme_sepia" to "Sepia Mode",
        "theme_sepia_desc" to "Warm paper texture for serene reading comfort",

        // Font & Tajweed Screen
        "font_screen_title" to "Font & Tajweed Settings",
        "tab_arabic_font" to "Arabic Script & Fonts",
        "tab_trans_font" to "Translation & Phonetics",
        "tab_tajweed_rules" to "Tajweed Color Guide",
        "arabic_font_style" to "Arabic Font Style",
        "arabic_script_style" to "Quran Script Style",
        "arabic_font_size" to "Arabic Font Size",
        "arabic_line_spacing" to "Arabic Line Spacing",
        "trans_font_size" to "Translation Font Size",
        "trans_font_style" to "Translation Font Style",
        "show_translation" to "Show Translation",
        "show_transliteration" to "Show Word Transliteration",
        "show_tajweed" to "Enable Color-Coded Tajweed",
        "show_waqf" to "Highlight Waqf / Pause Signs",
        "font_preview_title" to "Live Preview",
        "font_preview_arabic" to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "font_preview_trans" to "In the name of Allah, the Entirely Merciful, the Especially Merciful.",
        "reset_font_defaults" to "Reset to Defaults",

        // Notifications Screen
        "notif_screen_title" to "Notification Settings",
        "notif_banner_title" to "Smart Islamic Reminders",
        "notif_banner_desc" to "Receive timely notifications for daily verses, hadiths, and spiritual events.",
        "notif_daily_ayah" to "Daily Quran Verse",
        "notif_daily_ayah_desc" to "Selected Quran verse with translation every day",
        "notif_daily_hadith" to "Daily Hadith & Wisdom",
        "notif_daily_hadith_desc" to "Authentic hadiths and daily spiritual reflections",
        "notif_islamic_events" to "Islamic Events & Reminders",
        "notif_islamic_events_desc" to "Reminders for Friday, Laylatul Qadr, Eid, and special days",
        "notif_durood" to "Durood Sharif Reminder",
        "notif_durood_desc" to "Periodic reminders to send blessings upon the Prophet ﷺ",
        "notif_istighfar" to "Istighfar Reminder",
        "notif_istighfar_desc" to "Daily reminders for seeking Allah's forgiveness",
        "notif_sound_label" to "Notification Sound",
        "notif_vibrate_label" to "Vibration",
        "notif_time_select" to "Select Preferred Time",
        "notif_interval_select" to "Reminder Frequency",

        // Profile & Stats
        "stats_read_time" to "Total Reading Time",
        "stats_surahs_read" to "Surahs Read",
        "stats_total_ayahs" to "Verses Recited",
        "stats_streak" to "Daily Reading Streak",
        "stats_bookmarks" to "Total Bookmarks",
        "stats_notes" to "Notes Created",
        "stats_khatam_count" to "Khatams Completed",
        "profile_edit_name" to "Edit Display Name",
        "profile_user_placeholder" to "Quran Reader",

        // Bookmarks & Notes
        "bookmarks_empty" to "No bookmarks saved yet",
        "bookmarks_empty_desc" to "Tap the bookmark icon while reading any Surah, Ayah, or Mushaf page to save it.",
        "notes_empty" to "Your notepad is currently empty",
        "notes_empty_desc" to "Record your reflections, tafsir notes, and spiritual insights here.",
        "new_note" to "Create New Note",
        "note_title_hint" to "Note title...",
        "note_body_hint" to "Write your thoughts, tafsir notes, or reflections...",
        "note_saved" to "Note saved successfully",
        "note_deleted" to "Note deleted",

        // Planner Screen
        "planner_title" to "Quran Completion Planner",
        "planner_target" to "Khatam Target & Plan",
        "planner_daily_target" to "Daily Target",
        "planner_days_left" to "Days Remaining",
        "planner_progress" to "Overall Completion",
        "planner_mark_today_done" to "Mark Today's Portion as Read",
        "planner_reset" to "Reset Planner",

        // Offline Download Screen
        "offline_title" to "Offline Quran Download",
        "offline_desc" to "Download high-definition Mushaf pages, audio recitations, and tafsir for offline reading.",
        "offline_mushaf_pages" to "Mushaf Pages & Images",
        "offline_audio" to "Audio Recitations",
        "offline_tafsir" to "Tafsir & Word Meaning Data",
        "offline_storage_used" to "Storage Used",
        "offline_download_all" to "Download Complete Offline Package",
        "offline_clear_cache" to "Clear Cache",

        // Backup & Restore
        "backup_title" to "Backup & Restore",
        "backup_desc" to "Safeguard your bookmarks, personal notes, and reading progress.",
        "backup_create" to "Create New Backup",
        "backup_restore" to "Restore from Backup File",
        "backup_last_date" to "Last Backup: %s",
        "backup_success" to "Backup created successfully",
        "backup_restore_success" to "Data restored successfully",

        // About & Contact
        "about_title" to "About Us & Privacy",
        "about_app_desc" to "An ad-free, pristine, and premium Quran reading platform designed to facilitate accurate recitation, deep understanding, and spiritual elevation.",
        "about_features_title" to "Key Features",
        "about_developer_title" to "Development & Credits",
        "about_privacy_policy" to "Privacy Policy & Terms",
        "contact_title" to "Contact & Feedback",
        "contact_desc" to "Feel free to reach out to us with any suggestions, corrections, or feedback.",
        "contact_email" to "Send Email",
        "contact_telegram" to "Telegram Channel",
        "contact_facebook" to "Facebook Community",
        "contact_send_msg" to "Send Message Directly",
        "contact_subject_hint" to "Subject...",
        "contact_message_hint" to "Write your message or feedback here..."
    )

    // --- ARABIC (العربية) STRINGS ---
    private val AR_STRINGS = mapOf(
        // Menu & General
        "menu_title" to "خيارات القائمة",
        "close" to "إغلاق",
        "back" to "رجوع",
        "save" to "حفظ",
        "cancel" to "إلغاء",
        "delete" to "حذف",
        "edit" to "تعديل",
        "search" to "بحث",
        "details" to "التفاصيل",
        "confirm" to "تأكيد",
        "done" to "تم",
        "share" to "مشاركة",
        "download" to "تحميل",
        "refresh" to "تحديث",
        "all" to "الكل",
        "enabled" to "مفعل",
        "disabled" to "معطل",
        "system_default" to "تلقائي للنظام",
        "reset" to "إعادة ضبط",
        "play" to "تشغيل",
        "pause" to "إيقاف مؤقت",
        "copy" to "نسخ",
        "copied" to "تم النسخ إلى الحافظة",
        "success" to "نجاح",
        "error" to "خطأ",
        "loading" to "جاري التحميل...",
        "profile_title" to "ملفي الشخصي",
        "profile_stats" to "الملف الشخصي وإحصائيات القراءة",
        "profile_desc" to "تقدم قراءة القرآن والمعلومات الشخصية",

        // Menu Categories
        "cat_quran_media" to "دراسة القرآن والإعلام",
        "cat_dua_worship" to "الأدعية والعبادة",
        "cat_personal_tools" to "الأدوات الشخصية",
        "cat_app_settings" to "إعدادات النظام والتطبيق",

        // Menu Items
        "item_subjectwise" to "مواضيع القرآن",
        "item_learn" to "تعلم القرآن",
        "item_hifz" to "تحفيظ القرآن ومتابعة الحفظ",
        "item_player" to "مشغل التلاوات الصوتية",
        "item_video" to "صانع الفيديو القرآني",
        "item_dua" to "الأدعية القرآنية",
        "item_morning_evening_dua" to "أذكار الصباح والمساء",
        "item_mosque" to "المساجد القريبة",
        "item_manzil" to "آيات المنزل والشفاء",
        "item_qibla" to "بوصلة القبلة",
        "item_prayer_times" to "مواقيت الصلاة",
        "item_prayer_alarms" to "تنبيهات الصلاة والأذان",
        "item_calendar" to "التقويم الهجري الإسلامي",
        "item_planner" to "مخطط ختم القرآن",
        "item_bookmark" to "الإشارات المرجعية",
        "item_note" to "دفتر الملاحظات",
        "item_game" to "لعبة الكلمات القرآنية",
        "item_language" to "لغة التطبيق (Language)",
        "item_font_settings" to "الخط والتجويد",
        "item_theme" to "مظهر التطبيق",
        "item_notifications" to "إعدادات الإشعارات",
        "item_offline_sync" to "التحميل بدون إنترنت",
        "item_backup" to "النسخ الاحتياطي والاستعادة",
        "item_about" to "حول التطبيق والخصوصية",
        "item_contact" to "اتصل بنا والدعم",

        // Quick Settings
        "quick_settings_title" to "الإعدادات السريعة والتحكم",
        "quick_lang_label" to "لغة التطبيق",
        "quick_font_label" to "خط المصحف",
        "quick_theme_label" to "مظهر التطبيق",
        "quick_screen_on_label" to "إبقاء الشاشة مفعلة أثناء القراءة",

        // Language Screen
        "lang_screen_title" to "إعدادات اللغة / Language",
        "lang_banner_title" to "اختيار لغة التطبيق",
        "lang_banner_desc" to "اختر لغتك المفضلة، وسيتكيف التطبيق بالكامل مع اللغة المحددة.",
        "lang_bn_title" to "বাংলা",
        "lang_bn_desc" to "বাংলা (البنغالية) - الواجهة الافتراضية",
        "lang_en_title" to "English",
        "lang_en_desc" to "English - الواجهة الإنجليزية",
        "lang_ar_title" to "العربية",
        "lang_ar_desc" to "العربية (Arabic) - الواجهة العربية بالكامل",
        "lang_switched_bn" to "تم تغيير لغة التطبيق إلى البنغالية",
        "lang_switched_en" to "تم تغيير لغة التطبيق إلى الإنجليزية",
        "lang_switched_ar" to "تم تغيير لغة التطبيق إلى العربية بنجاح",

        // Theme Screen
        "theme_screen_title" to "اختيار مظهر التطبيق",
        "theme_banner_title" to "السمات ووضع العرض",
        "theme_banner_desc" to "اختر مظهر القراءة المفضل لراحة عينيك أثناء التلاوة.",
        "theme_system" to "تلقائي للنظام",
        "theme_system_desc" to "يتبع إعدادات الوضع الداكن/الفاتح للجهاز",
        "theme_light" to "الوضع الفاتح (Light)",
        "theme_light_desc" to "خلفية بيضاء نقية وواضحة للقراءة النهارية",
        "theme_dark" to "الوضع الداكن (Dark)",
        "theme_dark_desc" to "خلفية هادئة مريحة للعين مخصصة للقراءة الليلية",
        "theme_oled" to "أسود OLED النقي",
        "theme_oled_desc" to "خلفية سوداء تماماً موفرة لاستهلاك البطارية",
        "theme_sepia" to "وضع سيبيا الورقي (Sepia)",
        "theme_sepia_desc" to "لون ورق المصاحف التراثي لراحة وسكينة أثناء القراءة",

        // Font & Tajweed Screen
        "font_screen_title" to "إعدادات الخط والتجويد",
        "tab_arabic_font" to "الخط العربي ورسم المصحف",
        "tab_trans_font" to "الترجمة والصوتيات",
        "tab_tajweed_rules" to "دليل ألوان أحكام التجويد",
        "arabic_font_style" to "نوع الخط العربي",
        "arabic_script_style" to "رسم المصحف الشريف",
        "arabic_font_size" to "حجم الخط العربي",
        "arabic_line_spacing" to "تباعد الأسطر",
        "trans_font_size" to "حجم خط الترجمة",
        "trans_font_style" to "نوع خط الترجمة",
        "show_translation" to "عرض الترجمة",
        "show_transliteration" to "عرض النطق الصوتي للكلمات",
        "show_tajweed" to "تفعيل ألوان أحكام التجويد",
        "show_waqf" to "إبراز علامات الوقف والوصل",
        "font_preview_title" to "معاينة حية",
        "font_preview_arabic" to "بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ",
        "font_preview_trans" to "الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ",
        "reset_font_defaults" to "استعادة الإعدادات الافتراضية",

        // Notifications Screen
        "notif_screen_title" to "إعدادات الإشعارات والتنبيهات",
        "notif_banner_title" to "التنبيهات الإسلامية الذكية",
        "notif_banner_desc" to "تلقَّ إشعارات دورية للآيات اليومية والأحاديث والمناسبات والأذكار.",
        "notif_daily_ayah" to "آية قرآنية يومية",
        "notif_daily_ayah_desc" to "آية مختارة مع التفسير والترجمة كل يوم",
        "notif_daily_hadith" to "حديث نبوي يومي وحكمة",
        "notif_daily_hadith_desc" to "أحاديث نبوية صحيحة ورسائل روحانية يومية",
        "notif_islamic_events" to "المناسبات الإسلامية",
        "notif_islamic_events_desc" to "تذكير بيوم الجمعة، وليالي القدر، والأعياد والمناسبات",
        "notif_durood" to "تذكير الصلاة على النبي ﷺ",
        "notif_durood_desc" to "تنبيهات منتظمة للصلاة والسلام على رسول الله ﷺ",
        "notif_istighfar" to "تذكير الاستغفار والتوبة",
        "notif_istighfar_desc" to "تذكير يومي لترطيب اللسان بذكر الله والاستغفار",
        "notif_sound_label" to "صوت الإشعار",
        "notif_vibrate_label" to "الاهتزاز",
        "notif_time_select" to "تحديد الوقت المناسب",
        "notif_interval_select" to "تكرار التنبيه",

        // Profile & Stats
        "stats_read_time" to "إجمالي وقت القراءة",
        "stats_surahs_read" to "السور المقروءة",
        "stats_total_ayahs" to "الآيات المتلوة",
        "stats_streak" to "أيام القراءة المتتالية",
        "stats_bookmarks" to "الإشارات المرجعية",
        "stats_notes" to "الملاحظات المسجلة",
        "stats_khatam_count" to "الختمات المكتملة",
        "profile_edit_name" to "تعديل الاسم",
        "profile_user_placeholder" to "قارئ القرآن",

        // Bookmarks & Notes
        "bookmarks_empty" to "لا توجد إشارات مرجعية محفوظة",
        "bookmarks_empty_desc" to "اضغط على أيقونة الإشارة المرجعية أثناء تلاوة أي سورة أو آية لحفظها هنا.",
        "notes_empty" to "دفتر الملاحظات فارغ حالياً",
        "notes_empty_desc" to "سجل تأملاتك وتدبرك وفوائدك التفسيرية هنا.",
        "new_note" to "تدوين ملاحظة جديدة",
        "note_title_hint" to "عنوان الملاحظة...",
        "note_body_hint" to "اكتب خواطرك وتدبرك التفسيري هنا...",
        "note_saved" to "تم حفظ الملاحظة بنجاح",
        "note_deleted" to "تم حذف الملاحظة",

        // Planner Screen
        "planner_title" to "مخطط ختم القرآن الكريم",
        "planner_target" to "الهدف وخطة الختم",
        "planner_daily_target" to "الورد اليومي",
        "planner_days_left" to "الأيام المتبقية",
        "planner_progress" to "نسبة الإنجاز الكلية",
        "planner_mark_today_done" to "تحديد ورد اليوم كمكتمل",
        "planner_reset" to "إعادة ضبط المخطط",

        // Offline Download Screen
        "offline_title" to "تحميل القرآن للعمل بدون إنترنت",
        "offline_desc" to "قم بتحميل صفحات المصحف والتلاوات الصوتية وكتب التفسير للتلاوة دون اتصال.",
        "offline_mushaf_pages" to "صفحات المصحف الشريف",
        "offline_audio" to "التلاوات الصوتية",
        "offline_tafsir" to "بيانات التفسير ومعاني الكلمات",
        "offline_storage_used" to "المساحة المستخدمة",
        "offline_download_all" to "تحميل حزمة المصحف الكاملة",
        "offline_clear_cache" to "مسح الذاكرة المؤقتة",

        // Backup & Restore
        "backup_title" to "النسخ الاحتياطي والاستعادة",
        "backup_desc" to "حافظ على إشاراتك المرجعية وملاحظاتك وتقدم قراءتك في أمان.",
        "backup_create" to "إنشاء نسخة احتياطية جديدة",
        "backup_restore" to "استعادة البيانات من ملف",
        "backup_last_date" to "آخر نسخة احتياطية: %s",
        "backup_success" to "تم إنشاء النسخة الاحتياطية بنجاح",
        "backup_restore_success" to "تمت استعادة البيانات بنجاح",

        // About & Contact
        "about_title" to "حول التطبيق وسياسة الخصوصية",
        "about_app_desc" to "تطبيق قرآني إسلامي متكامل وخالٍ تماماً من الإعلانات، يهدف إلى تسهيل التلاوة والتدبر والارتقاء الروحي.",
        "about_features_title" to "أبرز مميزات التطبيق",
        "about_developer_title" to "فريق التطوير والاعتمادات",
        "about_privacy_policy" to "سياسة الخصوصية والشروط",
        "contact_title" to "اتصل بنا والدعم الفني",
        "contact_desc" to "يسعدنا دائماً تواصلكم معنا لأي اقتراح أو تصويب أو استفسار.",
        "contact_email" to "إرسال بريد إلكتروني",
        "contact_telegram" to "قناة تيليجرام",
        "contact_facebook" to "مجتمع فيسبوك",
        "contact_send_msg" to "إرسال رسالة مباشرة",
        "contact_subject_hint" to "الموضوع...",
        "contact_message_hint" to "اكتب رسالتك أو اقتراحك هنا..."
    )
}
